M48
; DRILL file {KiCad 7.0.11} date Wednesday, October 30, 2024 at 01:42:56 PM
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-10-30T13:42:56+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.000
%
G90
G05
T1
X151.13Y-78.57
X151.13Y-102.37
X174.43Y-78.57
X174.43Y-102.37
M30
